# Generated by Django 5.0.4 on 2024-05-01 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='created_by',
        ),
    ]
