# Generated by Django 5.0.4 on 2024-05-01 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_tasks_assigned_to_remove_tasks_created_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
